/* ----------------------------------------------------------------------
   SPARTA - Stochastic PArallel Rarefied-gas Time-accurate Analyzer
   http://sparta.github.io
   Steve Plimpton, sjplimp@gmail.com, Michael Gallis, magalli@sandia.gov
   Sandia National Laboratories

   Copyright (2014) Sandia Corporation.  Under the terms of Contract
   DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government retains
   certain rights in this software.  This software is distributed under
   the GNU General Public License.

   See the README file in the top-level SPARTA directory.
------------------------------------------------------------------------- */

#ifdef FIX_CLASS

FixStyle(cell/gradient,FixCellGrad)

#else

#ifndef SPARTA_FIX_CELL_GRAD_H
#define SPARTA_FIX_CELL_GRAD_H

#include "stdio.h"
#include "fix.h"

namespace SPARTA_NS {

class FixCellGrad : public Fix {
 public:
  FixCellGrad(class SPARTA *, int, char **);
  virtual ~FixCellGrad();
  int setmask();
  void init();
  void face_flux_premove(Particle::OnePart *, int);
  void update_cell_bulk(Particle::OnePart *, int, double);
  void face_flux_postmove(Particle::OnePart *, int, int);
  void end_of_step();
  //double memory_usage();

 protected:

  int dim;
  int nglocal;
  double T_interval; //time interval for sampling crossings
  int aveflag;
  int nsample;

  int nvalues;
  int *faceids; // list of all face values
  int *cellids; // list of all cell values
  int cellbulkindex; // custom per-grid for cell center values
  int cellfaceindex; // custom per-grid for cell face values

  int *direction; // for end_of_step to direct how to compute outputs
  int *quantity; // what to accumulate

  void reallocate();

};

}

#endif
#endif

/* ERROR/WARNING messages:

E: Illegal ... command

Self-explanatory.  Check the input script syntax and compare to the
documentation for the command.  You can use -echo screen as a
command-line option when running SPARTA to see the offending line.

E: Cannot open fix print file %s

The output file generated by the fix print command cannot be opened

*/
